"""
Heston model calibration to an implied volatility surface.

Workflow:
  1. generate_mock_surface(underlier, spot, risk_free_rate)
       Builds a synthetic IV grid from the default Heston parameters.
       Used until real ORATS data is available. Because the surface is
       generated by the same model, calibrating to it should recover the
       original parameters — this is the built-in correctness test.

  2. calibrate_heston(underlier, spot, risk_free_rate, vol_surface)
       Fits 5 Heston params by minimising squared IV errors using
       scipy L-BFGS-B with QuantLib's AnalyticHestonEngine as the pricer.

  3. save_calibrated / load_calibrated
       Persist results to data/calibrated/{TICKER}.json
"""

import json
from pathlib import Path

import numpy as np
import QuantLib as ql
from scipy.optimize import differential_evolution, minimize

from .heston import get_heston_params


CALIBRATED_DIR = Path(__file__).parent.parent / "data" / "calibrated"


# ---------------------------------------------------------------------------
# Mock vol surface generator
# ---------------------------------------------------------------------------


def generate_mock_surface(
    underlier: str,
    spot: float,
    risk_free_rate: float,
    dividend_yield: float = 0.0,
    today: ql.Date = None,
    strike_pcts: list = None,
    maturities: list = None,
) -> list:
    """
    Generate a synthetic IV surface using the default Heston parameters.

    The surface is a list of (strike, maturity_years, implied_vol) tuples.
    OTM options are used at each grid point for numerical stability:
      - Puts for strikes below spot (cheaper, less intrinsic value noise)
      - Calls for strikes at or above spot

    Put prices are converted to call prices via put-call parity before
    inverting to implied vol, so the calibration always works with calls.
    """
    if today is None:
        today = ql.Date.todaysDate()
    ql.Settings.instance().evaluationDate = today

    if strike_pcts is None:
        strike_pcts = [0.75, 0.80, 0.85, 0.90, 0.95, 1.00, 1.05, 1.10, 1.15, 1.20]
    if maturities is None:
        maturities = [1 / 12, 3 / 12, 6 / 12, 1.0, 1.5]

    p = get_heston_params(underlier)
    dc = ql.Actual365Fixed()
    rf_ts = ql.YieldTermStructureHandle(ql.FlatForward(today, risk_free_rate, dc))
    dv_ts = ql.YieldTermStructureHandle(ql.FlatForward(today, dividend_yield, dc))

    process = ql.HestonProcess(
        rf_ts,
        dv_ts,
        ql.QuoteHandle(ql.SimpleQuote(spot)),
        p["v0"],
        p["kappa"],
        p["theta"],
        p["sigma"],
        p["rho"],
    )
    model = ql.HestonModel(process)
    engine = ql.AnalyticHestonEngine(model)

    surface = []
    for mat in maturities:
        expiry = today + ql.Period(int(mat * 365), ql.Days)
        t = dc.yearFraction(today, expiry)
        fwd = spot * np.exp((risk_free_rate - dividend_yield) * t)
        df = np.exp(-risk_free_rate * t)

        for pct in strike_pcts:
            strike = spot * pct
            opt_type = ql.Option.Put if pct < 1.0 else ql.Option.Call

            payoff = ql.PlainVanillaPayoff(opt_type, strike)
            exercise = ql.EuropeanExercise(expiry)
            opt = ql.VanillaOption(payoff, exercise)
            opt.setPricingEngine(engine)
            price = opt.NPV()

            call_price = price + df * (fwd - strike) if opt_type == ql.Option.Put else price

            try:
                stddev = ql.blackFormulaImpliedStdDev(
                    ql.Option.Call, strike, fwd, call_price, df
                )
                iv = stddev / np.sqrt(t)
                if 0.01 < iv < 5.0:
                    surface.append((round(strike, 4), round(mat, 6), round(float(iv), 6)))
            except Exception:
                pass

    return surface


# ---------------------------------------------------------------------------
# Calibration engine
# ---------------------------------------------------------------------------


def calibrate_heston(
    underlier: str,
    spot: float,
    risk_free_rate: float,
    vol_surface: list,
    dividend_yield: float = 0.0,
    today: ql.Date = None,
    use_de: bool = False,
) -> dict:
    """
    Fit Heston parameters to a vol surface.

    Optimizer (§8.1):
      Default — scipy L-BFGS-B with bounded constraints.
      use_de=True — differential evolution global search first, then L-BFGS-B polish.

    Bounds (§8.1): kappa [0.5,8], theta [0.01,0.5], sigma [0.1,2.5],
                   rho [-0.95,-0.1], v0 [0.01,0.6]

    Feller condition (§8.2): 2·kappa·theta > sigma². Logged in result dict.
    """
    if today is None:
        today = ql.Date.todaysDate()
    ql.Settings.instance().evaluationDate = today

    dc = ql.Actual365Fixed()
    rf_ts = ql.YieldTermStructureHandle(ql.FlatForward(today, risk_free_rate, dc))
    dv_ts = ql.YieldTermStructureHandle(ql.FlatForward(today, dividend_yield, dc))
    spot_q = ql.QuoteHandle(ql.SimpleQuote(spot))

    bounds = [
        (0.50, 8.0),      # kappa
        (0.01, 0.5),      # theta
        (0.10, 2.5),      # sigma
        (-0.95, -0.10),   # rho
        (0.01, 0.6),      # v0
    ]

    def objective(x):
        kappa, theta, sigma, rho, v0 = x
        try:
            process = ql.HestonProcess(rf_ts, dv_ts, spot_q, v0, kappa, theta, sigma, rho)
            model = ql.HestonModel(process)
            engine = ql.AnalyticHestonEngine(model)

            sq_errors = []
            for strike, mat, market_iv in vol_surface:
                expiry = today + ql.Period(int(mat * 365), ql.Days)
                t = dc.yearFraction(today, expiry)
                fwd = spot * np.exp((risk_free_rate - dividend_yield) * t)
                df_ = np.exp(-risk_free_rate * t)

                payoff = ql.PlainVanillaPayoff(ql.Option.Call, strike)
                exercise = ql.EuropeanExercise(expiry)
                opt = ql.VanillaOption(payoff, exercise)
                opt.setPricingEngine(engine)

                try:
                    price = opt.NPV()
                    stddev = ql.blackFormulaImpliedStdDev(
                        ql.Option.Call, strike, fwd, price, df_
                    )
                    model_iv = stddev / np.sqrt(t)
                    sq_errors.append((model_iv - market_iv) ** 2)
                except Exception:
                    sq_errors.append(1.0)

            return float(np.mean(sq_errors))
        except Exception:
            return 1e6

    if use_de:
        de_result = differential_evolution(
            objective,
            bounds=bounds,
            seed=42,
            maxiter=200,
            popsize=8,
            tol=1e-8,
            polish=True,
        )
        best_x = de_result.x
        converged = bool(de_result.success)
        fun = de_result.fun
    else:
        p0 = get_heston_params(underlier)
        x0 = [p0["kappa"], p0["theta"], p0["sigma"], p0["rho"], p0["v0"]]
        lbfgs = minimize(
            objective,
            x0,
            method="L-BFGS-B",
            bounds=bounds,
            options={"maxiter": 500, "ftol": 1e-12, "gtol": 1e-8},
        )
        best_x = lbfgs.x
        converged = bool(lbfgs.success)
        fun = lbfgs.fun

    kappa, theta, sigma, rho, v0 = best_x
    feller = bool(2 * kappa * theta > sigma**2)

    return {
        "underlier": underlier.upper(),
        "v0": round(float(v0), 6),
        "kappa": round(float(kappa), 6),
        "theta": round(float(theta), 6),
        "sigma": round(float(sigma), 6),
        "rho": round(float(rho), 6),
        "dividend_yield": round(float(dividend_yield), 6),
        "rmse": round(float(np.sqrt(max(fun, 0))), 6),
        "converged": converged,
        "n_points": len(vol_surface),
        "feller_satisfied": feller,
    }


# ---------------------------------------------------------------------------
# QuantLib LevenbergMarquardt calibration
# ---------------------------------------------------------------------------


def calibrate_heston_ql(
    eval_date,
    spot,
    r,
    q,
    calibration_set,
    initial_params: dict = None,
):
    """
    Fit Heston parameters using QuantLib's native LevenbergMarquardt optimizer.
    """
    ql.Settings.instance().evaluationDate = eval_date
    spot_h = ql.QuoteHandle(ql.SimpleQuote(spot))
    rate_ts = ql.YieldTermStructureHandle(
        ql.FlatForward(eval_date, r, ql.Actual365Fixed())
    )
    div_ts = ql.YieldTermStructureHandle(
        ql.FlatForward(eval_date, q, ql.Actual365Fixed())
    )

    p = initial_params or {}
    v0 = p.get("v0", 0.10)
    kappa = p.get("kappa", 2.0)
    theta = p.get("theta", 0.10)
    sigma = p.get("sigma", 0.50)
    rho = p.get("rho", -0.50)

    process = ql.HestonProcess(rate_ts, div_ts, spot_h, v0, kappa, theta, sigma, rho)
    model = ql.HestonModel(process)
    engine = ql.AnalyticHestonEngine(model)

    helpers = []
    for q_pt in calibration_set:
        period = ql.Period(int(q_pt["expiry"] - eval_date), ql.Days)
        vol = ql.QuoteHandle(ql.SimpleQuote(q_pt["iv"]))
        h = ql.HestonModelHelper(
            period,
            ql.NullCalendar(),
            spot,
            q_pt["strike"],
            vol,
            rate_ts,
            div_ts,
        )
        h.setPricingEngine(engine)
        helpers.append(h)

    lm = ql.LevenbergMarquardt(1e-8, 1e-8, 1e-8)
    model.calibrate(helpers, lm, ql.EndCriteria(500, 50, 1e-8, 1e-8, 1e-8))

    v0, kappa, theta, sigma, rho = (
        model.params()[0],
        model.params()[1],
        model.params()[2],
        model.params()[3],
        model.params()[4],
    )

    residuals = [h.calibrationError() for h in helpers]
    return model, dict(v0=v0, kappa=kappa, theta=theta, sigma=sigma, rho=rho), residuals


def calibrate_heston_orats(
    underlier: str,
    eval_date,
    spot: float,
    r: float,
    calibration_set: list,
    q: float = 0.0,
) -> dict:
    """
    Calibrate Heston to a real ORATS surface.

    Converts the calibration set (ql.Date expiries) to the scipy-compatible
    (strike, maturity_years, iv) format and delegates to calibrate_heston().
    """
    vol_surface = [
        (pt["strike"], (pt["expiry"] - eval_date) / 365.0, pt["iv"])
        for pt in calibration_set
    ]
    return calibrate_heston(
        underlier,
        spot,
        r,
        vol_surface,
        dividend_yield=q,
        today=eval_date,
    )


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------


def save_calibrated(params: dict, out_dir: Path = CALIBRATED_DIR) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{params['underlier']}.json"
    path.write_text(json.dumps(params, indent=2))
    return path


def load_calibrated(underlier: str, calibrated_dir: Path = CALIBRATED_DIR) -> dict:
    """Return calibrated params dict, or None if no calibration file exists."""
    path = calibrated_dir / f"{underlier.upper()}.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    keep = ("v0", "kappa", "theta", "sigma", "rho", "dividend_yield")
    return {k: data[k] for k in keep if k in data}